env:
  global:
  - REPO_DIR=Brion
  - BUILD_COMMIT=HEAD
  - BUILD_DEPENDS="numpy"
  - TEST_DEPENDS="numpy nose"
  - PLAT=x86_64
  - UNICODE_WIDTH=32
  - secure: aq9vP+KEBCNsd7ycxq4q70rTlENlyAS+OBI1vzerxwvUjxi6MkiwD+PrGd9uJu70zaIFsOyqjp3vs+vlrfSNItqiCwEJJlldP29Op6J++79p/i8SFHAZ8GjVlV2TbsBF7rGITf0l17KRKDyjvomgxpX0h5FhnFZ5oV8TW29jzugBB34I1w3+IjI88W/Cp/AJkRoqAXaVagSZ1wiD2yUxMVG/tUzkE5abj57h8qV5cpZAkVsBibva66ADu//p5kI1foWcsTJb5sbhmr7nEHH10oUDwgK2erfEu805QbxHcOjfQ2OAvZ6ESoEeJusYqpqj3v/mPOaEpD/xPPqUmJticW+M13Sn/kClT/LnfXFnntg5brsWm92xkZ+mxhY1nJ53g+fEQvKL48ElwZMB4jD9e+eY4iMFmSiF8RkvaKhL8UepHnb3OCW5C9VO93kUPJHJgiJns/aid5SMSlAbMIR4d54x5OOfx3btX7IakBVWr6ST5oW3tAEgUG0dTyS5o1Y7p26oi90KrsVaSTTkLqK96hky9+xESspekto/Urvytpst9M7YvSa8knLg2JN0JB5mmUZhFuGY06InY8kzrda+YiQdFt07C4quYG2IbmN+syVvna4AmLP0/IWmaqfs9tDaYeivfxaSSUEJD4SeRYO8KjiF7KJO2THlS2nfECplDm8=
language: generic
services: docker
dist: xenial
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/Library/Caches/Homebrew"
jobs:
  include:
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
install:
- set -e
- chmod +x run_me.sh
- "./run_me.sh"
after_success:
- pip install twine
- ls ${TRAVIS_BUILD_DIR}/dist
- twine upload --verbose -u __token__ -p ${PYPI_PASSWORD} ${TRAVIS_BUILD_DIR}/dist/*
